Repository binbashar/le-docker-leverage-toolbox, pull requests merged in 2023-02, with the labels that each got.

#41 Issue 40 can not sso login with new aws cli
  scripts/aws-sso/aws-sso-login.sh
  versions_to_build
Labels: bug, patch

#42 ISSUE-16 | Keyboard Interrupt handling
  scripts/aws-mfa/aws-mfa-entrypoint.sh
  versions_to_build
Labels: patch, fix

#33 ISSUE-3 Added Dockerfile for Debian based image
  .circleci/config.yml
  Dockerfile
  versions_to_build
Labels: enhancement, patch

#45 HOTFIX added flag to jq command
  scripts/aws-sso/aws-sso-login.sh
  versions_to_build
Labels: bug, minor
